export const ADD_USER_LOCATION = 'ADD_USER_LOCATION';

export enum RegisterActionTypes {
  REGISTER = 'REGISTER',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAILURE = 'REGISTER_FAILURE',
}

export enum LoginActionTypes {
  LOGIN = 'LOGIN',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
}

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export enum GetUserProfileActionTypes {
  GET_USER_PROFILE = 'GET_USER_PROFILE',
  GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS',
  GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE',
}

export enum AddUserPlaceTypes {
  ADD_USER_PLACE = 'ADD_USER_PLACE',
  ADD_USER_PLACE_SUCCESS = 'ADD_USER_PLACE_SUCCESS',
  ADD_USER_PLACE_FAILURE = 'ADD_USER_PLACE_FAILURE',
}

export enum DeleteUserPlaceTypes {
  DELETE_USER_PLACE = 'DELETE_USER_PLACE',
  DELETE_USER_PLACE_SUCCESS = 'DELETE_USER_PLACE_SUCCESS',
  DELETE_USER_PLACE_FAILURE = 'DELETE_USER_PLACE_FAILURE',
}

export enum GetUserPlacesActionTypes {
  GET_USER_PLACES = 'GET_USER_PLACES',
  GET_USER_PLACES_SUCCESS = 'GET_USER_PLACES_SUCCESS',
  GET_USER_PLACES_FAILURE = 'GET_USER_PLACES_FAILURE',
}

export enum GetPlacesCategoriesActionTypes {
  GET_PLACES_CATEGORIES = 'GET_PLACES_CATEGORIES',
  GET_PLACES_CATEGORIES_SUCCESS = 'GET_PLACES_CATEGORIES_SUCCESS',
  GET_PLACES_CATEGORIES_FAILURE = 'GET_PLACES_CATEGORIES_FAILURE',
}
