export const ADD_USER_LOCATION = 'ADD_USER_LOCATION';

export enum RegisterActionTypes {
  REGISTER = 'REGISTER',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAILURE = 'REGISTER_FAILURE',
}

export enum LoginActionTypes {
  LOGIN = 'LOGIN',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
}

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
